[package]
name = "harmony"
authors = ["Cryptex"]
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
ahash = "0.8"
axum = { version = "0.6", features = ["ws"] }
futures-util = "0"
rmp-serde = "1.1"
serde = { version = "1", features = ["derive"] }
simd-json = "0.7"
tokio = { version = "1", features = ["rt-multi-thread", "net", "time", "macros", "sync", "signal", "parking_lot"] }
essence = { git = "https://github.com/AdaptChat/essence", features = ["client", "db", "bincode"] }
pretty_env_logger = "0.4"
log = "0.4"
tower-http = { version = "0.3", default-features = false, features = ["trace"] }
governor = { version = "0.5", default-features = false, features = ["std", "quanta"] }
dotenv = "0"
lapin = "2"
deadpool-lapin = "0"
bincode = "2.0.0-rc.2"
flume = "0.10"
base64 = "0.21"
ring = "0.16.20"
