name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    
    - uses: dtolnay/rust-toolchain@stable
      with:
        toolchain: nightly
    
    - uses: Swatinem/rust-cache@v2
    
    - name: Build
      run: cargo build --verbose --profile ci

    - uses: actions/upload-artifact@v3
      with:
        name: debug-build
        path: target/debug/harmony
